[project]
name = "tis_fastmri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepinv>=0.3.3",
    "einx>=0.3.0",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "torch>=2.8.0",
]
